# Generated by Django 3.2.9 on 2021-11-08 11:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='dataInicio',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 8, 8, 39, 11, 854655)),
        ),
        migrations.AlterField(
            model_name='fiap',
            name='dataFinal',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 8, 8, 39, 11, 856671), null=True),
        ),
        migrations.AlterField(
            model_name='fiap',
            name='dataInicio',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 8, 8, 39, 11, 856671)),
        ),
        migrations.AlterField(
            model_name='observacao',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 8, 8, 39, 11, 858672)),
        ),
    ]
