# Generated by Django 3.2.8 on 2021-11-09 11:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211108_0839'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Importancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Satisfacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='uploadCsv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('File', models.FileField(null=True, upload_to='imports/%y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('identificador', models.CharField(max_length=30)),
                ('senha', models.CharField(max_length=50)),
                ('nivelAcesso', models.CharField(choices=[('1', 'Aluno'), ('2', 'Professor'), ('3', 'Analista'), ('4', 'Coordenador')], default='1', max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='fiap',
            name='colaborador',
        ),
        migrations.AddField(
            model_name='aluno',
            name='cpf',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='turma',
            name='cod_turma',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='fiap',
            name='dataFinal',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 9, 8, 8, 51, 396633), null=True),
        ),
        migrations.AlterField(
            model_name='fiap',
            name='dataInicio',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 9, 8, 8, 51, 396633)),
        ),
        migrations.AlterField(
            model_name='observacao',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 9, 8, 8, 51, 398616)),
        ),
        migrations.AlterField(
            model_name='turma',
            name='dataInicio',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 9, 8, 8, 51, 394632)),
        ),
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=200)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.aluno')),
                ('importancia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.importancia')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pergunta')),
                ('satisfacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.satisfacao')),
            ],
        ),
        migrations.AddField(
            model_name='fiap',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.usuario'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.usuario'),
        ),
        migrations.DeleteModel(
            name='Colaborador',
        ),
    ]
