# Generated by Django 3.2.7 on 2021-09-22 12:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('ra', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Assinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docente', models.ImageField(blank=True, upload_to='docente/%y/%m/%d/')),
                ('coordenador', models.ImageField(blank=True, upload_to='coordenador/%y/%m/%d/')),
                ('social', models.ImageField(blank=True, upload_to='social/%y/%m/%d/')),
                ('aluno', models.ImageField(blank=True, upload_to='aluno/%y/%m/%d/')),
                ('responsavel', models.ImageField(blank=True, upload_to='responsavel/%y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('nif', models.CharField(max_length=11)),
                ('senha', models.CharField(max_length=50)),
                ('nivelAcesso', models.CharField(choices=[('1', 'Aluno'), ('2', 'Professor'), ('3', 'Analista'), ('4', 'Coordenador')], default='1', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Fiap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progresso', models.CharField(choices=[('1', 'Iniciada'), ('2', 'Em Análise'), ('3', 'Finalizada')], default='1', max_length=20)),
                ('dataInicio', models.DateTimeField(default=datetime.datetime(2021, 9, 22, 9, 58, 36, 822065))),
                ('dataFinal', models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 22, 9, 58, 36, 822065))),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.aluno')),
                ('assinatura', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.assinatura')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.colaborador')),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('periodo', models.CharField(choices=[('1', 'Manhã'), ('2', 'Tarde'), ('3', 'Noite')], default='1', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advverbal', models.BooleanField(default=False)),
                ('advescrita', models.BooleanField(default=False)),
                ('afastamento', models.BooleanField(default=False)),
                ('cancelmatricula', models.BooleanField(default=False)),
                ('fiap', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.fiap')),
            ],
        ),
        migrations.CreateModel(
            name='Observacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.CharField(max_length=500)),
                ('data', models.DateTimeField(default=datetime.datetime(2021, 9, 22, 9, 58, 36, 824064))),
                ('fiap', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.fiap')),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.colaborador')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.turma')),
            ],
        ),
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aulasprevistas', models.IntegerField()),
                ('ausencias', models.IntegerField()),
                ('fiap', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.fiap')),
            ],
        ),
        migrations.AddField(
            model_name='fiap',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.turma'),
        ),
        migrations.CreateModel(
            name='Aproveitamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notamedia', models.IntegerField()),
                ('notaaluno', models.IntegerField()),
                ('notarec', models.IntegerField()),
                ('fiap', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.fiap')),
                ('materia', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.materia')),
            ],
        ),
        migrations.CreateModel(
            name='Aprendizagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atencao', models.BooleanField(default=False)),
                ('compreensao', models.BooleanField(default=False)),
                ('comprometimento', models.BooleanField(default=False)),
                ('relacionamento', models.BooleanField(default=False)),
                ('Outros', models.CharField(max_length=100)),
                ('fiap', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.fiap')),
            ],
        ),
        migrations.AddField(
            model_name='aluno',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.turma'),
        ),
    ]
