# Generated by Django 3.2.7 on 2021-09-22 13:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='nivelAcesso',
            field=models.CharField(choices=[('1', 'Professor'), ('2', 'Analista'), ('3', 'Coordenador')], default='1', max_length=15),
        ),
        migrations.AlterField(
            model_name='fiap',
            name='dataFinal',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 22, 10, 36, 10, 512807)),
        ),
        migrations.AlterField(
            model_name='fiap',
            name='dataInicio',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 22, 10, 36, 10, 512807)),
        ),
        migrations.AlterField(
            model_name='observacao',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 22, 10, 36, 10, 515806)),
        ),
    ]
