# Generated by Django 3.2.7 on 2021-09-22 13:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210922_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assinatura',
            name='aluno',
            field=models.ImageField(null=True, upload_to='aluno/%y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='assinatura',
            name='coordenador',
            field=models.ImageField(null=True, upload_to='coordenador/%y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='assinatura',
            name='docente',
            field=models.ImageField(null=True, upload_to='docente/%y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='assinatura',
            name='responsavel',
            field=models.ImageField(null=True, upload_to='responsavel/%y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='assinatura',
            name='social',
            field=models.ImageField(null=True, upload_to='social/%y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='fiap',
            name='assinatura',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.assinatura'),
        ),
        migrations.AlterField(
            model_name='fiap',
            name='dataFinal',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 22, 10, 45, 52, 239120), null=True),
        ),
        migrations.AlterField(
            model_name='fiap',
            name='dataInicio',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 22, 10, 45, 52, 239120)),
        ),
        migrations.AlterField(
            model_name='observacao',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 22, 10, 45, 52, 241138)),
        ),
    ]
