# Generated by Django 3.2.7 on 2021-09-22 13:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210922_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aprendizagem',
            name='Outros',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aprendizagem',
            name='atencao',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='aprendizagem',
            name='compreensao',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='aprendizagem',
            name='comprometimento',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='aprendizagem',
            name='relacionamento',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='aproveitamento',
            name='notarec',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fiap',
            name='dataFinal',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 22, 10, 54, 32, 658432), null=True),
        ),
        migrations.AlterField(
            model_name='fiap',
            name='dataInicio',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 22, 10, 54, 32, 658432)),
        ),
        migrations.AlterField(
            model_name='observacao',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 22, 10, 54, 32, 660432)),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='advescrita',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='advverbal',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='afastamento',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='cancelmatricula',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
