# Generated by Django 3.2.7 on 2021-11-05 11:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20211019_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aprendizagem',
            name='fiap',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='home.fiap'),
        ),
        migrations.AlterField(
            model_name='aproveitamento',
            name='fiap',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='home.fiap'),
        ),
        migrations.AlterField(
            model_name='aproveitamento',
            name='materia',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='home.materia'),
        ),
        migrations.AlterField(
            model_name='fiap',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.aluno'),
        ),
        migrations.AlterField(
            model_name='fiap',
            name='assinatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.assinatura'),
        ),
        migrations.AlterField(
            model_name='fiap',
            name='colaborador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.colaborador'),
        ),
        migrations.AlterField(
            model_name='fiap',
            name='dataFinal',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 5, 8, 13, 38, 691276), null=True),
        ),
        migrations.AlterField(
            model_name='fiap',
            name='dataInicio',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 5, 8, 13, 38, 691276)),
        ),
        migrations.AlterField(
            model_name='fiap',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.turma'),
        ),
        migrations.AlterField(
            model_name='frequencia',
            name='fiap',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='home.fiap'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.colaborador'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.turma'),
        ),
        migrations.AlterField(
            model_name='observacao',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 5, 8, 13, 38, 693275)),
        ),
        migrations.AlterField(
            model_name='observacao',
            name='fiap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.fiap'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='fiap',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='home.fiap'),
        ),
    ]
